"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence, useReducedMotion } from "motion/react";
import { ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronRight, Code2, FileCheck2, Fingerprint, Layers3, LockKeyhole, MessageSquare, Play, ShieldCheck, Sparkles, Wallet } from "lucide-react";
import { Logo } from "@/components/brand/logo";
import { Dialog, DialogContent, DialogHeader } from "@/components/ui/dialog";
import { DemoButtons } from "@/components/auth/auth-form";
const stages = [
 {name:"Agree",icon:MessageSquare,title:"From a chat to a clear plan",text:"A shared scope. A real deadline. No awkward surprises."},
 {name:"Deliver",icon:FileCheck2,title:"Good work deserves clear feedback",text:"See what passed, what needs a revision, and why."},
 {name:"Get paid",icon:Wallet,title:"Close the loop with confidence",text:"Approve the work or agree on a resolution together."},
];
function Preview({stage}:{stage:number}) {
 return <div className="product-preview">
  <div className="preview-toolbar"><span className="preview-dots"><i/><i/><i/></span><span>Lantern Coffee / Brand illustration</span><LockKeyhole size={13}/></div>
  <div className="preview-body">
   <div className="preview-top"><span className="preview-label">PROJECT ROOM</span><span className="preview-live"><i/> In progress</span></div>
   <h3>A little warmth.<br/>A whole new look.</h3>
   <div className="preview-people"><span className="mini-avatar">MC</span><span className="mini-avatar mint">AR</span><span>Maya & Ana <CheckCheck size={13}/></span></div>
   <div className="preview-art"><div className="art-sun"/><div className="art-orbit o1"/><div className="art-orbit o2"/><div className="coffee-bag"><span>LANTERN</span><div className="bag-mark">✳</div><b>Holiday<br/>Blend</b><small>WARMTH, SHARED.</small></div><div className="art-caption">A BRIEF WORTH<br/>BRINGING TO LIFE.</div></div>
   <AnimatePresence mode="wait"><motion.div key={stage} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.25}} className="preview-result">
    <div className="result-icon">{stage===0?<Fingerprint/>:stage===1?<Sparkles/>:<CheckCheck/>}</div><div><b>{["Same brief. Both signatures.","Every finding has evidence.","Approved. Payment released."][stage]}</b><span>{["2 concepts · 2 revisions · $350","Style, format, and scope reviewed","PayPal sandbox · $350.00"][stage]}</span></div><Check className="result-check" size={18}/>
   </motion.div></AnimatePresence><div className="preview-assurance"><ShieldCheck size={13}/><span>Built on a shared agreement.</span></div>
  </div>
 </div>;
}
export function Landing() {
 const [stage,setStage]=useState(0); const [walkthrough,setWalkthrough]=useState<number|null>(null); const [demo,setDemo]=useState(false); const reduced=useReducedMotion();
 useEffect(()=>{if(reduced)return;const timer=setInterval(()=>setStage(s=>(s+1)%3),4500);return()=>clearInterval(timer);},[reduced]);
 const reveal={initial:{opacity:0,y:reduced?0:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.6}};
 return <div className="kept-site">
  <header className="site-nav"><div className="site-wrap nav-inner"><Logo/><nav aria-label="Main navigation"><a href="#how">How it works</a><a href="#review">AI review</a><a href="#agents">For agents</a></nav><div className="nav-actions"><Link href="/login">Sign in</Link><Link className="site-button small" href="/signup">Get started <ArrowUpRight size={15}/></Link></div></div></header>
  <main id="main">
   <div className="hero-scene"><div className="ambient-orb orb-one"/><div className="ambient-orb orb-two"/><div className="hero-grid"/><section className="site-wrap site-hero">
    <motion.div {...reveal} className="hero-copy"><div className="eyebrow"><span/> LESS CHASING. MORE CREATING.</div><h1>Great work.<br/>Clear terms.<br/><span>Promises kept.</span></h1><p>From the first message to the final payment. A better way to work together, with PayPal and an AI second opinion.</p><div className="hero-actions"><Link className="site-button" href="/signup">Start a pact <ArrowUpRight size={18}/></Link><button className="site-button secondary" onClick={()=>setDemo(true)}><Play size={15}/> Explore the demo</button></div><div className="hero-note"><span className="tiny-check"><Check size={11}/></span> AI credits included <span>·</span> Your work, your terms</div></motion.div>
    <motion.div {...reveal} transition={{duration:.8,delay:.15}} className="hero-product"><div className="product-halo"/><div className="orbit-label orbit-label-top"><MessageSquare size={14}/><span>“Let’s make something great.”</span></div><Preview stage={stage}/><div className="preview-progress">{stages.map((item,i)=><button key={item.name} onClick={()=>setStage(i)} className={i===stage?"active":""} aria-label={`Preview ${item.name}`}><item.icon size={13}/>{item.name}<span/></button>)}</div></motion.div>
   </section></div>
   <div className="site-wrap trust-row"><span>A little more certainty on both sides.</span><div><LockKeyhole size={16}/> PayPal payments</div><div><Sparkles size={16}/> Evidence-led AI</div><div><Fingerprint size={16}/> Signed by both</div></div>
   <section id="how" className="site-wrap workflow-section"><motion.div {...reveal} className="section-heading"><div><span className="eyebrow">A BETTER WAY TO WORK</span><h2>One place.<br/>From “let’s do it” to done.</h2></div><p>Keep the conversation wherever it started.<br/>Bring the agreement here.</p></motion.div><div className="workflow-grid">{stages.map((s,i)=><motion.button {...reveal} transition={{duration:.5,delay:i*.08}} key={s.name} className={`workflow-card ${stage===i?'selected':''}`} onClick={()=>{setStage(i);setWalkthrough(i);}}><span className="workflow-num">0{i+1}</span><s.icon size={28}/><h3>{s.name}</h3><p>{s.text}</p><span className="workflow-footer">{s.title}<ArrowRight size={16}/></span></motion.button>)}</div></section>
   <section id="review" className="site-wrap review-section"><motion.div {...reveal} className="review-visual"><div className="review-heading"><span><Sparkles size={18}/> AI review</span><span className="review-chip">Evidence first</span></div>{[{title:"Print-ready PNG",label:"Verified",detail:"2,400 × 2,400 pixels",ok:true},{title:"Two distinct concepts",label:"Verified",detail:"Both concepts are attached",ok:true},{title:"Warm, editorial style",label:"Your call",detail:"Compare with your agreed references",ok:false}].map((r,i)=><motion.div {...reveal} transition={{delay:i*.12}} className="review-line" key={r.title}><span className={r.ok?'check-circle':'question-circle'}>{r.ok?<Check size={15}/>:"?"}</span><div><b>{r.title}</b><small>{r.detail}</small></div><span>{r.label}</span></motion.div>)}<div className="review-bottom"><div className="mini-avatar mint">AR</div><p>“I can see exactly what to improve.”</p></div></motion.div><motion.div {...reveal} className="review-copy"><span className="eyebrow">A SECOND OPINION. WITH RECEIPTS.</span><h2>Creative work<br/>isn’t a checkbox.</h2><p>Agree on references, audience, and style before signing. The referee explains its findings against that brief. When the evidence is uncertain, people decide.</p><div className="review-points"><span><Check size={16}/> Clear evidence for each criterion</span><span><Check size={16}/> Revisions before disagreements grow</span><span><Check size={16}/> Mediation only settles when both agree</span></div></motion.div></section>
   <section id="agents" className="site-wrap"><motion.div {...reveal} className="agent-strip"><div className="agent-icon"><Code2 size={27}/></div><div><span className="eyebrow">HUMANS. AGENTS. BETTER TOGETHER.</span><h3>The same safeguards, through an API.</h3><p>Let an agent draft, hire, submit work, and follow payment status.</p></div><Link href="/app/developers">Explore the API <ArrowUpRight size={18}/></Link></motion.div></section>
   <section className="site-wrap"><motion.div {...reveal} className="closing-card"><div className="closing-symbol"><Layers3 size={30}/></div><h2>Your next project.<br/>On the same page.</h2><p>Make the agreement as good as the work.</p><Link className="site-button" href="/signup">Make your first pact <ArrowUpRight size={18}/></Link><button className="text-button" onClick={()=>setDemo(true)}>Or try both sides of a demo <ChevronRight size={15}/></button></motion.div></section>
  </main><footer className="site-wrap site-footer"><Logo/><span>Clear agreements. Better working relationships.</span><p>Test release · PayPal sandbox · No real money moves.</p></footer>
  <Dialog open={walkthrough!==null} onOpenChange={open=>{if(!open)setWalkthrough(null);}}><DialogContent wide><DialogHeader title={stages[walkthrough??0].title} description={["Turn the conversation into an agreement both people understand.","Know what passed, what needs attention, and what the evidence cannot prove.","See where the money is, and decide the next step together."][walkthrough??0]}/><div className="walkthrough-visual">
    <div className="walkthrough-top"><span className="walkthrough-brand">K</span><span>Lantern Coffee <b>/ Project room</b></span><span className="walkthrough-example">Product preview</span></div>
    {walkthrough===0?<><div className="walkthrough-title"><Fingerprint size={22}/><div><small>SHARED AGREEMENT</small><h3>Holiday Blend illustration</h3></div></div><div className="walkthrough-metrics"><span><small>Milestone</small><b>Two concepts</b></span><span><small>Budget</small><b>$150.00</b></span><span><small>Revisions</small><b>2 rounds</b></span></div><div className="walkthrough-row"><Check size={15}/><span>Bag front and sticker in each concept</span></div><div className="walkthrough-row"><Check size={15}/><span>Warm editorial style, using agreed references</span></div><div className="walkthrough-row"><Check size={15}/><span>Review guidance agreed before signing</span></div><div className="walkthrough-signatures"><span><Fingerprint size={18}/><b>Maya Chen</b><small>Client · signed</small></span><span><Fingerprint size={18}/><b>Ana Reyes</b><small>Freelancer · signed</small></span></div></>:walkthrough===1?<><div className="walkthrough-title"><Sparkles size={22}/><div><small>EVIDENCE-LED REVIEW</small><h3>A finding for every criterion</h3></div></div><div className="walkthrough-finding"><span className="check-circle"><Check size={15}/></span><div><b>Two distinct concepts</b><p>Both submitted files show a bag front and sticker.</p></div><span className="walkthrough-tag">Verified</span></div><div className="walkthrough-finding"><span className="question-circle">?</span><div><b>Warm editorial style</b><p>Compare the visual treatment with the signed reference.</p></div><span className="walkthrough-tag amber">Needs review</span></div><div className="walkthrough-evidence"><small>WHY THIS MATTERS</small><p>Dimensions confirm the file size. They cannot establish whether the creative direction matches the brief.</p><span><ShieldCheck size={14}/> Uncertain findings need a person.</span></div></>:<><div className="walkthrough-title"><Wallet size={22}/><div><small>PAYMENT RECORD</small><h3>Every step, accounted for</h3></div></div><div className="walkthrough-payment"><span>Milestone amount</span><strong>$150<span>.00</span></strong><small>PayPal sandbox illustration</small></div><div className="walkthrough-row"><CheckCheck size={17}/><span>Client approves the work</span><b>Release</b></div><div className="walkthrough-row"><MessageSquare size={17}/><span>Something needs changing</span><b>Revise</b></div><div className="walkthrough-row"><ShieldCheck size={17}/><span>Both accept a settlement</span><b>Split</b></div><p className="walkthrough-footnote">Payout and refund receipts show their actual status. A proposed split only settles when both people accept.</p></>}
   </div><div className="walkthrough-actions"><ButtonLikeClose onClick={()=>setWalkthrough(null)}/><Link className="site-button" href="/signup">Start your own pact <ArrowUpRight size={15}/></Link></div></DialogContent></Dialog>
  <Dialog open={demo} onOpenChange={setDemo}><DialogContent><span className="eyebrow mb-4">TAKE A LOOK AROUND</span><DialogHeader title="Which side are you on?" description="A private workspace. Switch roles anytime."/><DemoButtons/></DialogContent></Dialog>
 </div>;
}

function ButtonLikeClose({onClick}:{onClick:()=>void}){return <button className="walkthrough-back" onClick={onClick}>Back to exploring</button>;}
