import { BookOpenCheck, GitCompareArrows, Globe, Repeat, ShieldAlert, Webhook } from "lucide-react";
import { Container, SectionHeading } from "./section";

const APIS = [
  {
    name: "Orders v2",
    endpoint: "/v2/checkout/orders",
    body: "One order per milestone, created and captured server-side. Pay Later and card included.",
  },
  {
    name: "JS SDK v6",
    endpoint: "PayPal · Pay Later · Card",
    body: "Checkout buttons in the pact page, including guest card checkout for clients without a PayPal account.",
  },
  {
    name: "Payouts",
    endpoint: "/v1/payments/payouts",
    body: "Releases 100% of the milestone to the freelancer, idempotent on sender_batch_id.",
  },
  {
    name: "Payments v2 · Refunds",
    endpoint: "captures/{id}/refund",
    body: "Partial refunds against the original capture, so split settlements land where the client paid.",
  },
  {
    name: "Webhooks",
    endpoint: "verify-webhook-signature",
    body: "Signature-verified and deduplicated. If the buyer’s browser closes after approving, Kept captures the order server-side.",
  },
  {
    name: "Log in with PayPal",
    endpoint: "OpenID Connect",
    body: "Freelancers connect a verified PayPal account, so payouts go to the right person.",
  },
  {
    name: "Disputes · chargeback shield",
    endpoint: "disputes/{id}/provide-evidence",
    body: "If a client disputes with PayPal directly, Kept freezes release and submits the signed pact and verdict as evidence.",
  },
  {
    name: "PayPal Server SDK",
    endpoint: "@paypal/paypal-server-sdk",
    body: "Typed Orders and Payments clients generated by APIMatic, with PayPal-Request-Id on every write.",
  },
];

const ENGINEERING = [
  { icon: BookOpenCheck, title: "Double-entry ledger", body: "Every journal must net to zero or it is rejected." },
  { icon: Repeat, title: "Idempotent PayPal calls", body: "PayPal-Request-Id on every write, sender_batch_id on every payout." },
  { icon: GitCompareArrows, title: "Compare-and-set state machine", body: "A milestone changes state exactly once, so money can’t move twice." },
  { icon: Webhook, title: "Verified, deduplicated webhooks", body: "Replays and retries are safe by construction." },
  { icon: Globe, title: "SSRF-safe fetching", body: "Deliverable URLs are probed without reaching private networks." },
  { icon: ShieldAlert, title: "Prompt-injection guard", body: "Deliverables are untrusted input, scanned before the referee reads them." },
];

const JOURNALS = [
  {
    memo: "Escrow funded via PayPal capture",
    lines: [
      ["paypal_cash", "960.10", ""],
      ["escrow_liability", "", "900.00"],
      ["fee_revenue", "", "26.10"],
      ["processing_collected", "", "34.00"],
    ],
  },
  {
    memo: "PayPal payout to freelancer",
    lines: [
      ["escrow_liability", "900.00", ""],
      ["paypal_cash", "", "900.00"],
    ],
  },
];

function Ledger() {
  return (
    <figure className="overflow-hidden rounded-2xl border border-line bg-card shadow-card">
      <div className="flex items-center justify-between border-b border-line px-5 py-3">
        <span className="font-mono text-[11px] uppercase tracking-[0.14em] text-ink-2/80">Ledger · $900 milestone</span>
        <span className="rounded-full border border-jade-100 bg-jade-50 px-2 py-0.5 text-[11px] font-medium text-jade-700">balanced</span>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full min-w-[340px] font-mono text-[12px]">
          <caption className="sr-only">Example double-entry journals for funding and releasing a $900 milestone</caption>
          <thead>
            <tr className="text-[10.5px] uppercase tracking-wider text-ink-2/75">
              <th scope="col" className="px-5 pb-1 pt-3 text-left font-medium">Account</th>
              <th scope="col" className="px-3 pb-1 pt-3 text-right font-medium">Debit</th>
              <th scope="col" className="px-5 pb-1 pt-3 text-right font-medium">Credit</th>
            </tr>
          </thead>
          {JOURNALS.map((j) => (
            <tbody key={j.memo} className="border-t border-dashed border-line-2 first-of-type:border-t-0">
              <tr>
                <th colSpan={3} scope="rowgroup" className="px-5 pb-1 pt-3 text-left font-sans text-[12px] font-medium text-ink">
                  {j.memo}
                </th>
              </tr>
              {j.lines.map(([acct, dr, cr]) => (
                <tr key={acct} className="text-ink-2">
                  <td className={"py-0.5 text-left " + (cr ? "pl-9 pr-5" : "px-5")}>{acct}</td>
                  <td className="num px-3 py-0.5 text-right">{dr}</td>
                  <td className="num px-5 py-0.5 text-right">{cr}</td>
                </tr>
              ))}
              <tr>
                <td colSpan={3} className="px-5 pb-3 pt-1 text-right text-[11px] text-jade-700">
                  Σ = 0.00 ✓
                </td>
              </tr>
            </tbody>
          ))}
        </table>
      </div>
      <figcaption className="border-t border-line bg-paper px-5 py-3 text-[11.5px] leading-snug text-ink-2/80">
        The PayPal fee actually charged is read back from the capture and booked too, so the books match PayPal to the cent.
      </figcaption>
    </figure>
  );
}

export function PayPalRails() {
  return (
    <section id="paypal" aria-labelledby="paypal-title" className="scroll-mt-16 py-16 sm:py-20">
      <Container>
        <SectionHeading
          split
          id="paypal-title"
          index="06"
          eyebrow="Built on PayPal"
          title={
            <>
              Real money rails, <span className="italic text-jade-600">engineered like it’s real money.</span>
            </>
          }
          lede="Every movement of money in Kept is a PayPal API call, and every PayPal call is idempotent, verified and written to a balanced ledger."
        />

        <div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-4">
          {APIS.map((a) => (
            <div key={a.name} className="flex min-w-0 flex-col gap-2.5 bg-card p-5">
              <div className="flex items-baseline justify-between gap-3">
                <h3 className="text-[15px] font-semibold tracking-tight">{a.name}</h3>
              </div>
              <code className="w-fit max-w-full truncate rounded-md bg-paper-2 px-2 py-1 font-mono text-[11px] text-ink-2">{a.endpoint}</code>
              <p className="text-[13.5px] leading-relaxed text-ink-2">{a.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 grid gap-12 lg:grid-cols-[minmax(0,1fr)_minmax(0,460px)] lg:gap-16">
          <div>
            <h3 className="display text-[32px] leading-tight sm:text-[38px]">Money can’t move twice.</h3>
            <p className="mt-3 max-w-xl text-[15.5px] leading-relaxed text-ink-2">
              Webhooks retry. Browsers close mid-checkout. People double-click. Kept is built so none of that matters.
            </p>
            <ul className="mt-8 grid gap-x-8 gap-y-6 sm:grid-cols-2">
              {ENGINEERING.map((e) => (
                <li key={e.title} className="flex gap-3">
                  <span className="flex size-8 shrink-0 items-center justify-center rounded-lg border border-line bg-card text-jade-600 shadow-card">
                    <e.icon className="size-4" aria-hidden />
                  </span>
                  <div>
                    <div className="text-[14.5px] font-semibold">{e.title}</div>
                    <div className="mt-0.5 text-[13.5px] leading-relaxed text-ink-2">{e.body}</div>
                  </div>
                </li>
              ))}
            </ul>
          </div>
          <div className="min-w-0">
            <Ledger />
          </div>
        </div>
      </Container>
    </section>
  );
}
