import {
  ApiError,
  CheckoutPaymentIntent,
  Client,
  Environment,
  ItemCategory,
  LogLevel,
  OrdersController,
  PaymentsController,
  PaypalExperienceUserAction,
  PaypalWalletContextShippingPreference,
  type Order,
} from "@paypal/paypal-server-sdk";
import { env } from "@/lib/env";
import { toCents, toPayPalValue } from "@/lib/money";
import { getAccessToken, PAYPAL_API_BASE, paypalRequest, PayPalApiError } from "./http";
import type {
  CaptureResult,
  CreatedOrder,
  CreateOrderInput,
  PayoutInput,
  PayoutResult,
  PayPalGateway,
  RefundInput,
  RefundResult,
  WebhookVerificationInput,
} from "./types";

/**
 * Real PayPal integration.
 *
 * Orders v2 and Payments v2 go through PayPal's official Server SDK
 * (@paypal/paypal-server-sdk, generated by APIMatic). Payouts, webhook
 * signature verification and identity are not covered by the SDK, so those
 * use the REST API directly with the same OAuth credentials.
 */
export class LivePayPalGateway implements PayPalGateway {
  readonly mode = env.paypal.environment === "live" ? ("live" as const) : ("sandbox" as const);
  private orders: OrdersController;
  private payments: PaymentsController;

  constructor() {
    const client = new Client({
      clientCredentialsAuthCredentials: {
        oAuthClientId: env.paypal.clientId,
        oAuthClientSecret: env.paypal.clientSecret,
      },
      timeout: 30_000,
      environment: env.paypal.environment === "live" ? Environment.Production : Environment.Sandbox,
      logging: { logLevel: LogLevel.Warn, logRequest: { logBody: false }, logResponse: { logHeaders: false } },
    });
    this.orders = new OrdersController(client);
    this.payments = new PaymentsController(client);
  }

  async createOrder(input: CreateOrderInput): Promise<CreatedOrder> {
    const { quote, currency } = input;
    const money = (cents: number) => ({ currencyCode: currency, value: toPayPalValue(cents) });
    try {
      const { result } = await this.orders.createOrder({
        paypalRequestId: input.requestId,
        prefer: "return=representation",
        body: {
          intent: CheckoutPaymentIntent.Capture,
          purchaseUnits: [
            {
              referenceId: input.milestoneId,
              customId: input.milestoneId,
              invoiceId: `${input.milestoneId}-${input.requestId.slice(-8)}`,
              description: truncate(`Escrow: ${input.pactTitle}; ${input.milestoneTitle}`, 127),
              softDescriptor: "KEPT ESCROW",
              amount: {
                currencyCode: currency,
                value: toPayPalValue(quote.totalCents),
                breakdown: { itemTotal: money(quote.totalCents) },
              },
              items: [
                {
                  name: truncate(`Milestone: ${input.milestoneTitle}`, 127),
                  description: "Held in escrow until the work is approved",
                  quantity: "1",
                  unitAmount: money(quote.milestoneCents),
                  category: ItemCategory.DigitalGoods,
                  sku: input.milestoneId,
                },
                {
                  // One flat protection fee (it also covers payment processing). Never a separate
                  // "PayPal fee" line: surcharging for paying with PayPal isn't allowed.
                  name: "Kept protection fee",
                  description: "Escrow, AI referee, mediation, payout and processing",
                  quantity: "1",
                  unitAmount: money(quote.platformFeeCents + quote.processingFeeCents),
                  category: ItemCategory.DigitalGoods,
                },
              ],
            },
          ],
          // Wallet-specific experience context only for approval-link flows; the v6 buttons (incl. guest
          // card checkout) expect a plain order, exactly like PayPal's official v6 sample integration.
          ...(input.flow === "redirect"
            ? {
              paymentSource: {
                paypal: {
                  experienceContext: {
                    brandName: env.paypal.brandName,
                    shippingPreference: PaypalWalletContextShippingPreference.NoShipping,
                    userAction: PaypalExperienceUserAction.PayNow,
                    returnUrl: `${env.appUrl}/app/pacts/${input.pactId}?paypal=return`,
                    cancelUrl: `${env.appUrl}/app/pacts/${input.pactId}?paypal=cancel`,
                  },
                },
              },
              }
            : {}),
        },
      });
      return {
        orderId: result.id!,
        status: result.status ?? "CREATED",
        approveUrl: result.links?.find((l) => l.rel === "payer-action" || l.rel === "approve")?.href,
        raw: result,
      };
    } catch (err) {
      throw toPayPalError(err);
    }
  }

  async captureOrder(orderId: string, requestId: string): Promise<CaptureResult> {
    try {
      const { result } = await this.orders.captureOrder({
        id: orderId,
        paypalRequestId: requestId,
        prefer: "return=representation",
      });
      return summarizeOrder(result);
    } catch (err) {
      const e = toPayPalError(err);
      // Already captured (e.g. a retried request or the webhook beat us): read the order instead.
      if (e instanceof PayPalApiError && e.issue === "ORDER_ALREADY_CAPTURED") return this.getOrder(orderId);
      throw e;
    }
  }

  async getOrder(orderId: string): Promise<CaptureResult> {
    try {
      const { result } = await this.orders.getOrder({ id: orderId });
      return summarizeOrder(result);
    } catch (err) {
      throw toPayPalError(err);
    }
  }

  async refundCapture(input: RefundInput): Promise<RefundResult> {
    try {
      const { result } = await this.payments.refundCapturedPayment({
        captureId: input.captureId,
        paypalRequestId: input.requestId,
        prefer: "return=representation",
        body: {
          amount: { currencyCode: input.currency, value: toPayPalValue(input.amountCents) },
          noteToPayer: truncate(input.note, 255),
        },
      });
      return { refundId: result.id!, status: result.status ?? "PENDING", raw: result };
    } catch (err) {
      throw toPayPalError(err);
    }
  }

  async createPayout(input: PayoutInput): Promise<PayoutResult> {
    const body = {
      sender_batch_header: {
        sender_batch_id: input.senderBatchId,
        email_subject: truncate(input.subject, 255),
        email_message: truncate(input.note, 1000),
      },
      items: [
        {
          ...(input.receiverEmail.startsWith("payer:")
            ? { recipient_type: "PAYPAL_ID", receiver: input.receiverEmail.slice("payer:".length) }
            : { recipient_type: "EMAIL", receiver: input.receiverEmail }),
          amount: { value: toPayPalValue(input.amountCents), currency: input.currency },
          note: truncate(input.note, 4000),
          sender_item_id: input.senderItemId,
          notification_language: "en-US",
        },
      ],
    };
    const res = await paypalRequest<PayoutBatchResponse>("POST", "/v1/payments/payouts", {
      body,
      requestId: input.senderBatchId,
    });
    const batchId = res.batch_header.payout_batch_id;
    // The create call is asynchronous; fetch the batch once to pick up the item id/status.
    try {
      return await this.getPayoutBatch(batchId);
    } catch {
      return {
        batchId,
        itemId: null,
        status: res.batch_header.batch_status,
        itemStatus: null,
        feeCents: null,
        raw: res,
      };
    }
  }

  async getPayoutBatch(batchId: string): Promise<PayoutResult> {
    const res = await paypalRequest<PayoutBatchResponse>("GET", `/v1/payments/payouts/${batchId}`);
    const item = res.items?.[0];
    return {
      batchId,
      itemId: item?.payout_item_id ?? null,
      status: res.batch_header.batch_status,
      itemStatus: item?.transaction_status ?? null,
      feeCents: res.batch_header.fees ? toCents(res.batch_header.fees.value) : null,
      raw: res,
    };
  }

  async provideDisputeEvidence(disputeId: string, notes: string): Promise<void> {
    await provideDisputeEvidenceLive(disputeId, notes);
  }

  async verifyWebhook({ headers, rawBody }: WebhookVerificationInput): Promise<boolean> {
    if (!env.paypal.webhookId) return false;
    // Splice the raw event in verbatim: re-serialising it (JSON.parse → stringify) can change
    // number/unicode formatting and make PayPal's signature check fail intermittently.
    const envelope = {
      auth_algo: headers.get("paypal-auth-algo"),
      cert_url: headers.get("paypal-cert-url"),
      transmission_id: headers.get("paypal-transmission-id"),
      transmission_sig: headers.get("paypal-transmission-sig"),
      transmission_time: headers.get("paypal-transmission-time"),
      webhook_id: env.paypal.webhookId,
    };
    const rawEnvelope = `${JSON.stringify(envelope).slice(0, -1)},"webhook_event":${rawBody}}`;
    const res = await paypalRequest<{ verification_status: string }>("POST", "/v1/notifications/verify-webhook-signature", {
      rawBody: rawEnvelope,
    });
    return res.verification_status === "SUCCESS";
  }
}

export async function provideDisputeEvidenceLive(disputeId: string, notes: string): Promise<void> {
  // provide-evidence is multipart: an `input` JSON part (+ optional evidence files).
  const form = new FormData();
  const input = { evidences: [{ evidence_type: "PROOF_OF_FULFILLMENT", notes: notes.slice(0, 2000) }] };
  form.append("input", new Blob([JSON.stringify(input)], { type: "application/json" }));
  const res = await fetch(`${PAYPAL_API_BASE}/v1/customer/disputes/${encodeURIComponent(disputeId)}/provide-evidence`, {
    method: "POST",
    headers: { Authorization: `Bearer ${await getAccessToken()}` },
    body: form,
    cache: "no-store",
  });
  if (!res.ok) {
    const body = await res.text();
    let parsed: unknown = body;
    try {
      parsed = JSON.parse(body);
    } catch {
      /* keep text */
    }
    throw new PayPalApiError(res.status, parsed, res.headers.get("paypal-debug-id") ?? undefined);
  }
}

interface PayoutBatchResponse {
  batch_header: {
    payout_batch_id: string;
    batch_status: string;
    fees?: { value: string; currency: string };
  };
  items?: { payout_item_id: string; transaction_status: string }[];
}

function summarizeOrder(order: Order): CaptureResult {
  const unit = order.purchaseUnits?.[0];
  const capture = unit?.payments?.captures?.[0];
  const fee = capture?.sellerReceivableBreakdown?.paypalFee?.value;
  return {
    orderId: order.id!,
    status: capture?.status ?? order.status ?? "UNKNOWN",
    captureId: capture?.id ?? null,
    amountCents: toCents(capture?.amount?.value ?? unit?.amount?.value ?? "0"),
    paypalFeeCents: fee ? toCents(fee) : null,
    payerEmail: order.payer?.emailAddress ?? order.paymentSource?.paypal?.emailAddress ?? null,
    payerId: order.payer?.payerId ?? order.paymentSource?.paypal?.accountId ?? null,
    customId: capture?.customId ?? unit?.customId ?? null,
    raw: order,
  };
}

function toPayPalError(err: unknown): Error {
  if (err instanceof ApiError) {
    let body: unknown = err.result;
    if (!body && typeof err.body === "string") {
      try {
        body = JSON.parse(err.body);
      } catch {
        body = err.body;
      }
    }
    return new PayPalApiError(err.statusCode, body, err.headers?.["paypal-debug-id"]);
  }
  return err instanceof Error ? err : new Error(String(err));
}

const truncate = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1)}…` : s);
